### ISSUE TITLE
ChoJSONReader with dynamic field levels

### ISSUE THREAD

**Issue by claudneto** [Cinchoo/ChoETL#6]
I need to save a JSON to CSV and I'm trying to use ChoETL, but when I use ChoJSONReader, it takes just the first level of my json.
How do I read this JSON for multi-level, if it's dynamic? I don't know how many levels it will have.
I tried using .WithField and it worked, but it's dynamic.

**Comment by Cinchoo** [comment]
Can u post sample JSON input as well as sample code you tried? Let me help you on it.

**Comment by claudneto** [comment]
It's a form json. In some cases, we have something like a table that user includes many informations (it's dynamic, because user can create N or none items).

I got an example on internet and my code is just like this:

```
using (var r = new ChoJSONReader("emp.json", configuration))
            {
                using (var w = new ChoCSVWriter("emp.csv").WithFirstLineHeader())
                {
                    w.Write(r);
                }
            }
```

**Comment by Cinchoo** [comment]
Json is hierarchical structure data, you will need to flatten out in order to create CSV file from it. 

The stackoverflow answer may give you some hint. 

https://stackoverflow.com/questions/42719562/convert-any-nested-json-string-to-csv/45120454#45120454

If you still need more help, please post sample json.

**Comment by Cinchoo** [comment]
Post sample json file.
